export const enum MarkEnum {
  Nightmare = 'nightmare',
  DaWu = 'dawu',
  KuangFeng = 'kuangfeng',
  Ren = 'ren',
  Wrath = 'nu',
  JunLve = 'junlve',
  Lie = 'lie',
  XueYi = 'xueyi',
  Ying = 'ying',
  Orange = 'orange',
  PveHuaShen = 'pve_huashen',
  Fu = 'fu',
  Ran = 'ran',
  Wei = 'dulie_wei',
  Jian = 'jian',
  BaoLi = 'baoli',
  DanXue = 'danxue',
}
